

---

- hosts: all
  become: true
  tasks:

  - name: install openvpn
    script: ../Bash/openvpn-install.sh
    environment:
      AUTO_INSTALL: y
      CLIENT: client
      DNS: 9

  - name: fetch the client ovpn config
    fetch:
      src: client.ovpn
      dest: /tmp/
      flat: true
